### ISSUE TITLE
Is there documentation and how should it be used?

### ISSUE THREAD

**Issue by hurrykee** [madebyfabian/nuxt-wordpress#4]

**Comment by madebyfabian** [comment]
Hi there! Currently this module does not include much, since I haven't had the time to implement it.

**Comment by hurrykee** [comment]
> Hi there! Currently this module does not include much, since I haven't had the time to implement it.

OK and Thanks, I look forward to more updates.

**Comment by madebyfabian** [comment]
Maybe you want to take a look at https://github.com/vernaillen/wpnuxt-module, looks like it's actively developed and using a similar plugins & modules stack to what I use (and intend to use with this module)
